# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish"

baseURL = "https://sghhhh.github.io/"
defaultContentLanguage = "zh-cn"
languageCode = "zh-cn"

enableRobotsTXT = true
buildFuture = true
[pagination]
  pagerSize = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"
