# -- Language Configuration --

languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "SG's Blog"

[params]
  displayName = "中文"
  isoCode = "zh-CN"
  dateFormat = "2006年1月2日"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "我的个人博客"
  # copyright = "© {year} SG"

[params.author]
  name = "SG"
  # image = "img/author.jpg"
  headline = "欢迎来到我的博客"
  bio = "一个热爱技术的人"
  links = [
    { github = "https://github.com/sghhhh" },
    # { twitter = "https://twitter.com/username" },
    # { email = "mailto:your@email.com" },
  ]
